services:
  server:
    build:
      context: ./rust_grpc_server
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    networks:
      - grpc_net
    healthcheck:
      test: ["CMD", "bash", "-c", "</dev/tcp/localhost/50051"]
      interval: 3s
      timeout: 2s
      retries: 5
  
  scaler_builder:
    build:
      context: ./python_client
      dockerfile: Dockerfile
    command: ["python3", "build_scaler.py"]
    volumes:
      - ../BaseballPred/dataset:/app/data
    networks:
      - grpc_net

  client:
    build:
      context: ./python_client
      dockerfile: Dockerfile
    environment:
      - GRPC_SERVER_ADDRESS=server:50051
    depends_on:
      server:
        condition: service_healthy
      scaler_builder:
        condition: service_completed_successfully
    volumes:
      - ../BaseballPred/dataset:/app/data
    networks:
      - grpc_net
    deploy:
      replicas: 4

networks:
  grpc_net:
    driver: bridge