syntax = "proto3";
package parameter_server;

service WeightsManager {
    rpc UpdateWeights (ModelUpdate) returns (WeightResponse);
    rpc RequestWeights (WeightsRequest) returns (ModelUpdate);
    rpc WakeWorker (GoodMorning) returns (WorkerRegistration);
}

message WeightResponse {
    bool success = 1;
}

message WeightsRequest {
    int32 worker_id = 1;
}

message LayerGradient {
    int32 id = 1;
    repeated float weights = 2;
}

message ModelUpdate {
    repeated LayerGradient layers = 1;
}

message GoodMorning {}

message WorkerRegistration {
    bool success = 1;
    int32 worker_id = 2;
    string path = 3;
}