services:
  network_map_producer:
    build:
      context: ./python_client
      dockerfile: Dockerfile
    command: ["python3", "produce_model_structure.py"]
    volumes:
      - ./python_client/network_map.json:/app/network_map.json

  server:
    build:
      context: ./rust_grpc_server
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      network_map_producer:
        condition: service_completed_successfully
    networks:
      - grpc_net
    volumes:
      - ./python_client/network_map.json:/app/network_map.json
      - ./results:/app/results
    healthcheck:
      test: ["CMD", "bash", "-c", "</dev/tcp/localhost/50051"]
      interval: 3s
      timeout: 2s
      retries: 5
  
  scaler_builder:
    build:
      context: ./python_client
      dockerfile: Dockerfile
    command: ["python3", "build_scaler.py"]
    volumes:
      - ./dataset:/app/data
      - ./results:/app/results
    networks:
      - grpc_net

  client:
    build:
      context: ./python_client
      dockerfile: Dockerfile
    environment:
      - GRPC_SERVER_ADDRESS=server:50051
    depends_on:
      server:
        condition: service_healthy
      scaler_builder:
        condition: service_completed_successfully
    volumes:
      - ./dataset:/app/data
      - ./results:/app/results
    networks:
      - grpc_net
    deploy:
      replicas: 4

networks:
  grpc_net:
    driver: bridge